name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          sudo ARCHFLAGS="-arch x86_64 -arch arm64" HDF5_DIR="/usr/local" pyinstaller --noconfirm --onedir --argv-emulation --windowed \
            --target-architecture universal2 \
            --exclude-module PIL \
            --exclude-module Pillow \
            --hidden-import h5py.defs \
            --hidden-import h5py.utils \
            --hidden-import h5py._proxy \
            --collect-data h5py \
            ${{ github.workspace }}/src/main.py \
            --icon=${{ github.workspace }}/resources/icon.icns \
            --add-data "${{ github.workspace }}/docs/_build/:." \
            --add-data "${{ github.workspace }}/src/helpers/mat/SzDetectCat.m:." \
            --add-data "${{ github.workspace }}/src/helpers/mat/save_channel_to_mat.m:." \
            --add-data "${{ github.workspace }}/src/helpers/mat/getChs.m:." \
            --add-data "${{ github.workspace }}/src/helpers/mat/get_cat_envelop.m:." \
            --additional-hooks-dir "${{ github.workspace }}/hooks/" \
            --add-data "${{ github.workspace }}/src/helpers/mat/*.m:." \
            --add-binary "/usr/local/opt/hdf5/lib/libhdf5.dylib:." \
            --add-binary "/usr/local/opt/hdf5/lib/libhdf5_hl.dylib:." \
            --add-binary "/opt/homebrew/opt/hdf5/lib/libhdf5.dylib:." \
            --add-binary "/opt/homebrew/opt/hdf5/lib/libhdf5_hl.dylib:."

          rm -rf ${{ github.workspace }}/package_root/MEA\\ GUI.app
          cp -R ${{ github.workspace }}/dist/main.app ${{ github.workspace }}/package_root/MEA\\ GUI.app
          cp ${{ github.workspace }}/resources/fonts/GeistMonoNerdFontMono-Regular.otf ${{ github.workspace }}/package_root/MEA\\ GUI.app/Contents/Resources/
          chmod -R 755 ${{ github.workspace }}/package_root/MEA\\ GUI.app
          pkgbuild --root ${{ github.workspace }}/package_root --identifier com.booka66.meagui --install-location / ${{ github.workspace }}/MEA_GUI_MacOS.pkg

      - name: Build with PyInstaller (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --collect-submodules=sz_se_detect --noconfirm  --onedir --windowed ${{ github.workspace }}/src/main.py --icon=${{ github.workspace }}/resources/icon.ico --add-data "${{ github.workspace }}/docs/_build/:." --add-data "${{ github.workspace }}/src/helpers/mat/SzDetectCat.m:." --add-data "${{ github.workspace }}/src/helpers/mat/save_channel_to_mat.m:." --add-data "${{ github.workspace }}/src/helpers/mat/getChs.m:." --add-data "${{ github.workspace }}/src/helpers/mat/get_cat_envelop.m:." --additional-hooks-dir "${{ github.workspace }}/hooks/" --add-data "${{ github.workspace }}/src/helpers/mat/*.m:." --add-data "${{ github.workspace }}/resources/fonts/GeistMonoNerdFontMono-Regular.otf"

          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /Q ${{ github.workspace }}\MEA_GUI_Installer.iss

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            ${{ github.workspace }}/MEA_GUI_MacOS.pkg
            ${{ github.workspace }}/Output/MEA_GUI_Windows.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: packages

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload macOS Package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: MEA_GUI_MacOS.pkg
          asset_name: MEA_GUI_MacOS.pkg
          asset_content_type: application/octet-stream

      - name: Upload Windows Package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: MEA_GUI_Windows.exe
          asset_name: MEA_GUI_Windows.exe
          asset_content_type: application/octet-stream
